name: Run Calendar Sync

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-calendar-sync]

  schedule:
    - cron: "0 22 * * 0-4"   # 08:00 AM AEST = 22:00 UTC previous day (Mon–Fri)
    - cron: "0 23 * * 0-4"   # 09:00 AM AEST = 23:00 UTC previous day (Mon–Fri)
    - cron: "0 1 * * 1-5"    # 11:00 AM AEST = 01:00 UTC (Mon–Fri)
    - cron: "0 3 * * 1-5"    # 01:00 PM AEST = 03:00 UTC (Mon–Fri)
    - cron: "0 5 * * 1-5"    # 03:00 PM AEST = 05:00 UTC (Mon–Fri)

jobs:
  calendar-sync:
    runs-on: ubuntu-latest

    steps:
      # -------------------- Checkout repo -------------------- #
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------- Set up Python -------------------- #
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # -------------------- Install Dependencies -------------------- #
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------- Authenticate with GCP -------------------- #
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SEC_FORMATTER }}

      # -------------------- Run Calendar Sync Script -------------------- #
      - name: Run Calendar Sync Script
        run: echo test, and deploy the data
